<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Designation;
use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'employee_id' => 'EMP-001',
                'full_name' => 'Md. Rakibul Hasan',
                'father_name' => 'Md. Abdul Karim',
                'mother_name' => 'Rahima Khatun',
                'email' => 'rakibul.hasan@realestate.test',
                'mobile' => '01711000001',
                'emergency_mobile' => '01811000001',
                'dob' => '1981-03-15',
                'present_address' => 'House 12, Road 5, Banani, Dhaka 1213',
                'permanent_address' => 'Village: Kaliganj, Lalmonirhat',
                'marital_status' => 'married',
                'passport_no' => 'BA1234567',
                'blood_group' => 'O+',
                'gender' => 'male',
                'age' => 45,
                'religion' => 'islam',
                'national_id' => '199012345678901',
                'nationality' => 'Bangladesh',
                'status' => 'active',
                'date_of_joining' => '2019-01-02',
                'position_applied_for' => 'Chief Executive Officer',
                'department' => 'Administration',
                'designation' => 'CEO',
                'designation_level' => 'Executive',
                'employment_type' => 'full_time',
                'monthly_salary' => 250000,
                'functional_superior_name' => 'Board of Directors',
                'highest_degree' => 'MBA',
                'institution' => 'University of Dhaka',
                'passing_year' => '2005',
                'cgpa' => '3.75',
            ],
            [
                'employee_id' => 'EMP-002',
                'full_name' => 'Farhana Akter',
                'father_name' => 'Md. Jalal Uddin',
                'mother_name' => 'Shirin Begum',
                'email' => 'farhana.akter@realestate.test',
                'mobile' => '01711000002',
                'emergency_mobile' => '01811000002',
                'dob' => '1988-07-22',
                'present_address' => 'Apartment 3B, House 45, Road 11, Dhanmondi, Dhaka 1209',
                'permanent_address' => 'Village: Charpara, Netrokona',
                'marital_status' => 'married',
                'passport_no' => null,
                'blood_group' => 'B+',
                'gender' => 'female',
                'age' => 38,
                'religion' => 'islam',
                'national_id' => '199211298765432',
                'nationality' => 'Bangladesh',
                'status' => 'active',
                'date_of_joining' => '2020-06-01',
                'position_applied_for' => 'HR Manager',
                'department' => 'Human Resources (HR)',
                'designation' => 'Manager',
                'designation_level' => 'Mid Level',
                'employment_type' => 'full_time',
                'monthly_salary' => 90000,
                'functional_superior_name' => 'Md. Rakibul Hasan',
                'highest_degree' => 'Masters in HRM',
                'institution' => 'North South University',
                'passing_year' => '2011',
                'cgpa' => '3.60',
            ],
            [
                'employee_id' => 'EMP-003',
                'full_name' => 'Arif Chowdhury',
                'father_name' => 'Late Nurul Islam',
                'mother_name' => 'Kohinoor Begum',
                'email' => 'arif.chowdhury@realestate.test',
                'mobile' => '01711000003',
                'emergency_mobile' => '01811000003',
                'dob' => '1984-11-05',
                'present_address' => 'House 7, Road 9, Gulshan 2, Dhaka 1212',
                'permanent_address' => 'Village: Hajipur, Cumilla',
                'marital_status' => 'married',
                'passport_no' => 'BA7654321',
                'blood_group' => 'A+',
                'gender' => 'male',
                'age' => 42,
                'religion' => 'islam',
                'national_id' => '198712345098765',
                'nationality' => 'Bangladesh',
                'status' => 'active',
                'date_of_joining' => '2018-04-10',
                'position_applied_for' => 'Senior Finance Manager',
                'department' => 'Finance and Accounts',
                'designation' => 'Senior Manager',
                'designation_level' => 'Senior Level',
                'employment_type' => 'full_time',
                'monthly_salary' => 120000,
                'functional_superior_name' => 'Md. Rakibul Hasan',
                'highest_degree' => 'MBA (Finance)',
                'institution' => 'IBA, University of Dhaka',
                'passing_year' => '2008',
                'cgpa' => '3.80',
            ],
            [
                'employee_id' => 'EMP-004',
                'full_name' => 'Sadia Islam',
                'father_name' => 'Md. Golam Mostafa',
                'mother_name' => 'Rokeya Sultana',
                'email' => 'sadia.islam@realestate.test',
                'mobile' => '01711000004',
                'emergency_mobile' => '01811000004',
                'dob' => '1996-02-14',
                'present_address' => 'House 22, Road 3, Mirpur 10, Dhaka 1216',
                'permanent_address' => 'Village: Ataikula, Pabna',
                'marital_status' => 'unmarried',
                'passport_no' => null,
                'blood_group' => 'AB+',
                'gender' => 'female',
                'age' => 30,
                'religion' => 'islam',
                'national_id' => '199616543210987',
                'nationality' => 'Bangladesh',
                'status' => 'active',
                'date_of_joining' => '2021-09-15',
                'position_applied_for' => 'Marketing Officer',
                'department' => 'Sales and Marketing',
                'designation' => 'Officer',
                'designation_level' => 'Entry Level',
                'employment_type' => 'full_time',
                'monthly_salary' => 45000,
                'functional_superior_name' => 'Farhana Akter',
                'highest_degree' => 'BBA (Marketing)',
                'institution' => 'East West University',
                'passing_year' => '2018',
                'cgpa' => '3.55',
            ],
            [
                'employee_id' => 'EMP-005',
                'full_name' => 'Tanvir Ahmed',
                'father_name' => 'Md. Shamsul Haque',
                'mother_name' => 'Nasima Akter',
                'email' => 'tanvir.ahmed@realestate.test',
                'mobile' => '01711000005',
                'emergency_mobile' => '01811000005',
                'dob' => '1993-09-30',
                'present_address' => 'House 40, Road 12, Uttara Sector 7, Dhaka 1230',
                'permanent_address' => 'Village: Baniachong, Habiganj',
                'marital_status' => 'unmarried',
                'passport_no' => null,
                'blood_group' => 'B-',
                'gender' => 'male',
                'age' => 33,
                'religion' => 'islam',
                'national_id' => '199412345678900',
                'nationality' => 'Bangladesh',
                'status' => 'active',
                'date_of_joining' => '2022-01-05',
                'position_applied_for' => 'IT Support Officer',
                'department' => 'Information Technology (IT)',
                'designation' => 'IT Officer',
                'designation_level' => 'Entry Level',
                'employment_type' => 'full_time',
                'monthly_salary' => 55000,
                'functional_superior_name' => 'Md. Rakibul Hasan',
                'highest_degree' => 'BSc in CSE',
                'institution' => 'BRAC University',
                'passing_year' => '2016',
                'cgpa' => '3.20',
            ],
            [
                'employee_id' => 'EMP-006',
                'full_name' => 'Nusrat Jahan',
                'father_name' => 'Md. Anwar Hossain',
                'mother_name' => 'Fatema Khatun',
                'email' => 'nusrat.jahan@realestate.test',
                'mobile' => '01711000006',
                'emergency_mobile' => '01811000006',
                'dob' => '1991-05-18',
                'present_address' => 'House 9, Road 7, Mohammadpur, Dhaka 1207',
                'permanent_address' => 'Village: Joypur, Sylhet',
                'marital_status' => 'married',
                'passport_no' => 'BA9876543',
                'blood_group' => 'O-',
                'gender' => 'female',
                'age' => 35,
                'religion' => 'islam',
                'national_id' => '199298765098763',
                'nationality' => 'Bangladesh',
                'status' => 'active',
                'date_of_joining' => '2019-11-01',
                'position_applied_for' => 'Operations Executive',
                'department' => 'Commercial & Operation',
                'designation' => 'Executive Officer',
                'designation_level' => 'Mid Level',
                'employment_type' => 'full_time',
                'monthly_salary' => 60000,
                'functional_superior_name' => 'Arif Chowdhury',
                'highest_degree' => 'MBA',
                'institution' => 'University of Chittagong',
                'passing_year' => '2014',
                'cgpa' => '3.45',
            ],
            [
                'employee_id' => 'EMP-007',
                'full_name' => 'Kamrul Hasan',
                'father_name' => 'Md. Bahar Uddin',
                'mother_name' => 'Jahanara Begum',
                'email' => 'kamrul.hasan@realestate.test',
                'mobile' => '01711000007',
                'emergency_mobile' => '01811000007',
                'dob' => '1979-12-01',
                'present_address' => 'Staff Quarter, 12/A Tejgaon Industrial Area, Dhaka 1208',
                'permanent_address' => 'Village: Gangni, Meherpur',
                'marital_status' => 'married',
                'passport_no' => null,
                'blood_group' => 'A-',
                'gender' => 'male',
                'age' => 47,
                'religion' => 'islam',
                'national_id' => '197912345678090',
                'nationality' => 'Bangladesh',
                'status' => 'active',
                'date_of_joining' => '2017-03-20',
                'position_applied_for' => 'Security Guard',
                'department' => 'Administration',
                'designation' => 'Security Guard',
                'designation_level' => 'Entry Level',
                'employment_type' => 'full_time',
                'monthly_salary' => 20000,
                'functional_superior_name' => 'Farhana Akter',
                'highest_degree' => 'SSC',
                'institution' => 'Meherpur High School',
                'passing_year' => '1997',
                'cgpa' => null,
            ],
            [
                'employee_id' => 'EMP-008',
                'full_name' => 'Mehedi Hassan',
                'father_name' => 'Md. Rafiqul Islam',
                'mother_name' => 'Salma Begum',
                'email' => 'mehedi.hassan@realestate.test',
                'mobile' => '01711000008',
                'emergency_mobile' => '01811000008',
                'dob' => '1998-08-09',
                'present_address' => 'House 15, Road 2, Eskaton Garden, Dhaka 1000',
                'permanent_address' => 'Village: Sonadanga, Khulna',
                'marital_status' => 'unmarried',
                'passport_no' => null,
                'blood_group' => 'B+',
                'gender' => 'male',
                'age' => 28,
                'religion' => 'islam',
                'national_id' => '199916543210988',
                'nationality' => 'Bangladesh',
                'status' => 'active',
                'date_of_joining' => '2023-07-01',
                'position_applied_for' => 'Graphics Designer',
                'department' => 'Sales and Marketing',
                'designation' => 'Graphics Designer',
                'designation_level' => 'Entry Level',
                'employment_type' => 'full_time',
                'monthly_salary' => 38000,
                'functional_superior_name' => 'Sadia Islam',
                'highest_degree' => 'BFA',
                'institution' => 'Bangladesh University of Creative Arts',
                'passing_year' => '2020',
                'cgpa' => '3.30',
            ],
            [
                'employee_id' => 'EMP-009',
                'full_name' => 'Rupa Begum',
                'father_name' => 'Md. Sirajul Islam',
                'mother_name' => 'Amena Khatun',
                'email' => 'rupa.begum@realestate.test',
                'mobile' => '01711000009',
                'emergency_mobile' => '01811000009',
                'dob' => '1989-04-25',
                'present_address' => 'House 33, Road 4, Mugda, Dhaka 1214',
                'permanent_address' => 'Village: Bhanga, Faridpur',
                'marital_status' => 'married',
                'passport_no' => null,
                'blood_group' => 'O+',
                'gender' => 'female',
                'age' => 37,
                'religion' => 'islam',
                'national_id' => '199012345678098',
                'nationality' => 'Bangladesh',
                'status' => 'active',
                'date_of_joining' => '2018-08-15',
                'position_applied_for' => 'Office Assistant',
                'department' => 'Administration',
                'designation' => 'Office Assistant',
                'designation_level' => 'Entry Level',
                'employment_type' => 'full_time',
                'monthly_salary' => 25000,
                'functional_superior_name' => 'Farhana Akter',
                'highest_degree' => 'HSC',
                'institution' => 'Faridpur Govt. College',
                'passing_year' => '2008',
                'cgpa' => null,
            ],
        ];

        foreach ($employees as $employee) {
            $department = Department::where('name', $employee['department'])->first();
            $designation = Designation::where('name', $employee['designation'])->first();

            unset($employee['department'], $employee['designation']);

            Employee::updateOrCreate(
                ['employee_id' => $employee['employee_id']],
                array_merge($employee, [
                    'department_id' => $department?->id,
                    'designation_id' => $designation?->id,
                    'status' => $employee['status'] ?? 'active',
                ]),
            );
        }
    }
}