<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $divisions = [
            ['id' => 1, 'name' => 'Dhaka'],
            ['id' => 2, 'name' => 'Chattogram'],
            ['id' => 3, 'name' => 'Rajshahi'],
            ['id' => 4, 'name' => 'Khulna'],
            ['id' => 5, 'name' => 'Barishal'],
            ['id' => 6, 'name' => 'Sylhet'],
            ['id' => 7, 'name' => 'Rangpur'],
            ['id' => 8, 'name' => 'Mymensingh'],
        ];
        DB::table('divisions')->insert($divisions);

        $districts = [
            ['id' => 1, 'division_id' => 1, 'name' => 'Dhaka'],
            ['id' => 2, 'division_id' => 1, 'name' => 'Gazipur'],
            ['id' => 3, 'division_id' => 1, 'name' => 'Narayanganj'],
            ['id' => 4, 'division_id' => 1, 'name' => 'Tangail'],
            ['id' => 5, 'division_id' => 1, 'name' => 'Kishoreganj'],
            ['id' => 6, 'division_id' => 1, 'name' => 'Manikganj'],
            ['id' => 7, 'division_id' => 1, 'name' => 'Munshiganj'],
            ['id' => 8, 'division_id' => 1, 'name' => 'Narsingdi'],
            ['id' => 9, 'division_id' => 1, 'name' => 'Faridpur'],
            ['id' => 10, 'division_id' => 1, 'name' => 'Gopalganj'],
            ['id' => 11, 'division_id' => 1, 'name' => 'Madaripur'],
            ['id' => 12, 'division_id' => 1, 'name' => 'Rajbari'],
            ['id' => 13, 'division_id' => 1, 'name' => 'Shariatpur'],
            ['id' => 14, 'division_id' => 2, 'name' => 'Chattogram'],
            ['id' => 15, 'division_id' => 2, 'name' => 'Cox\'s Bazar'],
            ['id' => 16, 'division_id' => 2, 'name' => 'Bandarban'],
            ['id' => 17, 'division_id' => 2, 'name' => 'Rangamati'],
            ['id' => 18, 'division_id' => 2, 'name' => 'Khagrachhari'],
            ['id' => 19, 'division_id' => 2, 'name' => 'Noakhali'],
            ['id' => 20, 'division_id' => 2, 'name' => 'Feni'],
            ['id' => 21, 'division_id' => 2, 'name' => 'Lakshmipur'],
            ['id' => 22, 'division_id' => 2, 'name' => 'Comilla'],
            ['id' => 23, 'division_id' => 2, 'name' => 'Brahmanbaria'],
            ['id' => 24, 'division_id' => 2, 'name' => 'Chandpur'],
            ['id' => 25, 'division_id' => 3, 'name' => 'Rajshahi'],
            ['id' => 26, 'division_id' => 3, 'name' => 'Natore'],
            ['id' => 27, 'division_id' => 3, 'name' => 'Sirajganj'],
            ['id' => 28, 'division_id' => 3, 'name' => 'Pabna'],
            ['id' => 29, 'division_id' => 3, 'name' => 'Bogra'],
            ['id' => 30, 'division_id' => 3, 'name' => 'Joypurhat'],
            ['id' => 31, 'division_id' => 3, 'name' => 'Naogaon'],
            ['id' => 32, 'division_id' => 3, 'name' => 'Nawabganj'],
            ['id' => 33, 'division_id' => 4, 'name' => 'Khulna'],
            ['id' => 34, 'division_id' => 4, 'name' => 'Bagerhat'],
            ['id' => 35, 'division_id' => 4, 'name' => 'Shatkhira'],
            ['id' => 36, 'division_id' => 4, 'name' => 'Jashore'],
            ['id' => 37, 'division_id' => 4, 'name' => 'Magura'],
            ['id' => 38, 'division_id' => 4, 'name' => 'Jhenaidah'],
            ['id' => 39, 'division_id' => 4, 'name' => 'Kushtia'],
            ['id' => 40, 'division_id' => 4, 'name' => 'Chuadanga'],
            ['id' => 41, 'division_id' => 4, 'name' => 'Meherpur'],
            ['id' => 42, 'division_id' => 5, 'name' => 'Barishal'],
            ['id' => 43, 'division_id' => 5, 'name' => 'Pirojpur'],
            ['id' => 44, 'division_id' => 5, 'name' => 'Bhola'],
            ['id' => 45, 'division_id' => 5, 'name' => 'Patuakhali'],
            ['id' => 46, 'division_id' => 5, 'name' => 'Barguna'],
            ['id' => 47, 'division_id' => 5, 'name' => 'Jhalokati'],
            ['id' => 48, 'division_id' => 6, 'name' => 'Sylhet'],
            ['id' => 49, 'division_id' => 6, 'name' => 'Moulvibazar'],
            ['id' => 50, 'division_id' => 6, 'name' => 'Habiganj'],
            ['id' => 51, 'division_id' => 6, 'name' => 'Sunamganj'],
            ['id' => 52, 'division_id' => 7, 'name' => 'Rangpur'],
            ['id' => 53, 'division_id' => 7, 'name' => 'Dinajpur'],
            ['id' => 54, 'division_id' => 7, 'name' => 'Thakurgaon'],
            ['id' => 55, 'division_id' => 7, 'name' => 'Panchagarh'],
            ['id' => 56, 'division_id' => 7, 'name' => 'Nilphamari'],
            ['id' => 57, 'division_id' => 7, 'name' => 'Lalmonirhat'],
            ['id' => 58, 'division_id' => 7, 'name' => 'Kurigram'],
            ['id' => 59, 'division_id' => 7, 'name' => 'Gaibandha'],
            ['id' => 60, 'division_id' => 8, 'name' => 'Mymensingh'],
            ['id' => 61, 'division_id' => 8, 'name' => 'Netrokona'],
            ['id' => 62, 'division_id' => 8, 'name' => 'Jamalpur'],
            ['id' => 63, 'division_id' => 8, 'name' => 'Sherpur'],
        ];
        DB::table('districts')->insert($districts);

        $thanas = [
            // Dhaka division thanas
            ['district_id' => 1, 'name' => 'Dhaka Sadar'],
            ['district_id' => 1, 'name' => 'Gulshan'],
            ['district_id' => 1, 'name' => 'Mirpur'],
            ['district_id' => 1, 'name' => 'Uttara'],
            ['district_id' => 1, 'name' => 'Motijheel'],
            ['district_id' => 1, 'name' => 'Dhanmondi'],
            ['district_id' => 1, 'name' => 'Mohammadpur'],
            ['district_id' => 1, 'name' => 'Tejgaon'],
            ['district_id' => 1, 'name' => 'Ramna'],
            ['district_id' => 1, 'name' => 'Savar'],
            ['district_id' => 2, 'name' => 'Gazipur Sadar'],
            ['district_id' => 2, 'name' => 'Kaliakair'],
            ['district_id' => 2, 'name' => 'Sreepur'],
            ['district_id' => 2, 'name' => 'Kapasia'],
            ['district_id' => 3, 'name' => 'Narayanganj Sadar'],
            ['district_id' => 3, 'name' => 'Fatullah'],
            ['district_id' => 3, 'name' => 'Siddhirganj'],
            ['district_id' => 3, 'name' => 'Bandar'],
            ['district_id' => 4, 'name' => 'Tangail Sadar'],
            ['district_id' => 4, 'name' => 'Kalihati'],
            ['district_id' => 4, 'name' => 'Mirzapur'],
            ['district_id' => 5, 'name' => 'Kishoreganj Sadar'],
            ['district_id' => 5, 'name' => 'Bhairab'],
            ['district_id' => 6, 'name' => 'Manikganj Sadar'],
            ['district_id' => 6, 'name' => 'Singair'],
            ['district_id' => 7, 'name' => 'Munshiganj Sadar'],
            ['district_id' => 7, 'name' => 'Sirajdikhan'],
            ['district_id' => 8, 'name' => 'Narsingdi Sadar'],
            ['district_id' => 8, 'name' => 'Monohardi'],
            ['district_id' => 9, 'name' => 'Faridpur Sadar'],
            ['district_id' => 9, 'name' => 'Alfadanga'],
            ['district_id' => 10, 'name' => 'Gopalganj Sadar'],
            ['district_id' => 10, 'name' => 'Tungipara'],
            ['district_id' => 11, 'name' => 'Madaripur Sadar'],
            ['district_id' => 12, 'name' => 'Rajbari Sadar'],
            ['district_id' => 13, 'name' => 'Shariatpur Sadar'],
            // Chattogram division thanas
            ['district_id' => 14, 'name' => 'Chattogram Sadar'],
            ['district_id' => 14, 'name' => 'Double Mooring'],
            ['district_id' => 14, 'name' => 'Pahartali'],
            ['district_id' => 14, 'name' => 'Patenga'],
            ['district_id' => 14, 'name' => 'Sitakunda'],
            ['district_id' => 14, 'name' => 'Mirsharai'],
            ['district_id' => 14, 'name' => 'Hathazari'],
            ['district_id' => 14, 'name' => 'Raojan'],
            ['district_id' => 15, 'name' => 'Cox\'s Bazar Sadar'],
            ['district_id' => 15, 'name' => 'Ukhia'],
            ['district_id' => 15, 'name' => 'Teknaf'],
            ['district_id' => 15, 'name' => 'Ramu'],
            ['district_id' => 16, 'name' => 'Bandarban Sadar'],
            ['district_id' => 17, 'name' => 'Rangamati Sadar'],
            ['district_id' => 18, 'name' => 'Khagrachhari Sadar'],
            ['district_id' => 19, 'name' => 'Noakhali Sadar'],
            ['district_id' => 19, 'name' => 'Begumganj'],
            ['district_id' => 20, 'name' => 'Feni Sadar'],
            ['district_id' => 21, 'name' => 'Lakshmipur Sadar'],
            ['district_id' => 22, 'name' => 'Comilla Sadar'],
            ['district_id' => 23, 'name' => 'Brahmanbaria Sadar'],
            ['district_id' => 24, 'name' => 'Chandpur Sadar'],
            // Rajshahi division thanas
            ['district_id' => 25, 'name' => 'Rajshahi Sadar'],
            ['district_id' => 25, 'name' => 'Boalia'],
            ['district_id' => 25, 'name' => 'Paba'],
            ['district_id' => 26, 'name' => 'Natore Sadar'],
            ['district_id' => 27, 'name' => 'Sirajganj Sadar'],
            ['district_id' => 28, 'name' => 'Pabna Sadar'],
            ['district_id' => 29, 'name' => 'Bogra Sadar'],
            ['district_id' => 30, 'name' => 'Joypurhat Sadar'],
            ['district_id' => 31, 'name' => 'Naogaon Sadar'],
            ['district_id' => 32, 'name' => 'Nawabganj Sadar'],
            // Khulna division thanas
            ['district_id' => 33, 'name' => 'Khulna Sadar'],
            ['district_id' => 33, 'name' => 'Khalishpur'],
            ['district_id' => 33, 'name' => 'Sonadanga'],
            ['district_id' => 34, 'name' => 'Bagerhat Sadar'],
            ['district_id' => 35, 'name' => 'Shatkhira Sadar'],
            ['district_id' => 36, 'name' => 'Jashore Sadar'],
            ['district_id' => 37, 'name' => 'Magura Sadar'],
            ['district_id' => 38, 'name' => 'Jhenaidah Sadar'],
            ['district_id' => 39, 'name' => 'Kushtia Sadar'],
            ['district_id' => 40, 'name' => 'Chuadanga Sadar'],
            ['district_id' => 41, 'name' => 'Meherpur Sadar'],
            // Barishal division thanas
            ['district_id' => 42, 'name' => 'Barishal Sadar'],
            ['district_id' => 42, 'name' => 'Kotwali'],
            ['district_id' => 43, 'name' => 'Pirojpur Sadar'],
            ['district_id' => 44, 'name' => 'Bhola Sadar'],
            ['district_id' => 45, 'name' => 'Patuakhali Sadar'],
            ['district_id' => 46, 'name' => 'Barguna Sadar'],
            ['district_id' => 47, 'name' => 'Jhalokati Sadar'],
            // Sylhet division thanas
            ['district_id' => 48, 'name' => 'Sylhet Sadar'],
            ['district_id' => 48, 'name' => 'Jalalabad'],
            ['district_id' => 48, 'name' => 'South Surma'],
            ['district_id' => 49, 'name' => 'Moulvibazar Sadar'],
            ['district_id' => 50, 'name' => 'Habiganj Sadar'],
            ['district_id' => 51, 'name' => 'Sunamganj Sadar'],
            // Rangpur division thanas
            ['district_id' => 52, 'name' => 'Rangpur Sadar'],
            ['district_id' => 53, 'name' => 'Dinajpur Sadar'],
            ['district_id' => 54, 'name' => 'Thakurgaon Sadar'],
            ['district_id' => 55, 'name' => 'Panchagarh Sadar'],
            ['district_id' => 56, 'name' => 'Nilphamari Sadar'],
            ['district_id' => 57, 'name' => 'Lalmonirhat Sadar'],
            ['district_id' => 58, 'name' => 'Kurigram Sadar'],
            ['district_id' => 59, 'name' => 'Gaibandha Sadar'],
            // Mymensingh division thanas
            ['district_id' => 60, 'name' => 'Mymensingh Sadar'],
            ['district_id' => 60, 'name' => 'Trishal'],
            ['district_id' => 61, 'name' => 'Netrokona Sadar'],
            ['district_id' => 62, 'name' => 'Jamalpur Sadar'],
            ['district_id' => 63, 'name' => 'Sherpur Sadar'],
        ];
        DB::table('thanas')->insert($thanas);
    }
}
